/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#00180a",
        "on-primary-fixed-variant": "#006824",
        "on-primary-fixed": "#004816",
        "primary-fixed": "#6bfc81",
        "on-tertiary-fixed-variant": "#005762",
        "on-tertiary-container": "#004d57",
        surface: "#001206",
        "tertiary-container": "#00e3fc",
        "tertiary-fixed-dim": "#00d4ec",
        "surface-container-highest": "#002d17",
        "surface-variant": "#002d17",
        "on-error-container": "#ffd2c8",
        "on-secondary": "#005d35",
        primary: "#6bfc81",
        "surface-tint": "#6bfc81",
        "secondary-container": "#006d3f",
        "surface-container-high": "#002612",
        "primary-fixed-dim": "#5bed74",
        "on-primary": "#005d1f",
        "surface-bright": "#00341b",
        "on-surface": "#ccfcd9",
        "outline-variant": "#255036",
        error: "#ff7351",
        "surface-dim": "#001206",
        tertiary: "#7fedff",
        secondary: "#7df7ae",
        "on-secondary-container": "#e2ffe7",
        "on-primary-container": "#002a09",
        "on-error": "#450900",
        "secondary-fixed-dim": "#6ee9a1",
        "on-background": "#ccfcd9",
        "inverse-primary": "#006f27",
        outline: "#537f62",
        "on-surface-variant": "#88b695",
        "secondary-fixed": "#7df7ae",
        "tertiary-fixed": "#00e3fc",
        "primary-container": "#11b948",
        "on-secondary-fixed": "#004828",
        "surface-container": "#001f0e",
        "on-secondary-fixed-variant": "#00673c",
        "on-tertiary": "#005761",
        background: "#001206",
        "surface-container-lowest": "#000000",
        "inverse-on-surface": "#335e43",
        "error-container": "#b92902",
        "inverse-surface": "#e9ffec",
        "on-tertiary-fixed": "#00383f",
        "tertiary-dim": "#00d4ec",
        "error-dim": "#d53d18",
        "secondary-dim": "#6ee9a1",
        "primary-dim": "#5bed74"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        sm: "12px",
        xl: "80px",
        gutter: "24px",
        "container-max": "1280px",
        lg: "48px",
        base: "8px",
        xs: "4px",
        md: "24px"
      },

      fontFamily: {
        caption: ["Inter", "sans-serif"],
        "headline-md": ["Quicksand", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Quicksand", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Quicksand", "sans-serif"],
        "headline-lg": ["Quicksand", "sans-serif"],
        headline: ["Quicksand", "sans-serif"],
        display: ["Quicksand", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      },
      fontSize: {
        caption: ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
